# Generated by Django 5.0.1 on 2024-02-08 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата производства'),
        ),
    ]
